const tripData = {
  trip: {
    title: 'Fukuoka Trip',
    subtitle: '福岡晚夏三日遊 --- / 吃爆福岡！買爆福岡！/',
    location: 'Fukuoka, Japan',
    startDate: '2026-09-03',
    endDate: '2026-09-05',
  },

  theme: {
    primary: '#D96846',
    secondary: '#F3C58F',
    background: '#FFF9F2',
    heroImage: './assets/hero-placeholder.svg',
    heroEmoji: '🍜',
  },
  flights: {
    outbound: {
      airline: '華航',
      flightNo: 'CI110',
      departureTime: '06:50',
      departureAirport: 'TPE 桃園',
      arrivalTime: '09:55',
      arrivalAirport: 'FUK 福岡',
    },
    inbound: {
      airline: '華航',
      flightNo: 'CI129',
      departureTime: '19:10',
      departureAirport: 'FUK 福岡',
      arrivalTime: '20:35',
      arrivalAirport: 'TPE 桃園',
    },
  },
  hotel: {
    name: '福岡博多車站東方飯店 Oriental Hotel Fukuoka Hakata Station',
    address: '4-23 Hakataekichuogai, Hakata Ward, Fukuoka, 812-0012日本',
    mapUrl: 'https://maps.app.goo.gl/LMuzC42K2QnVxDVr8',
    websiteUrl: 'https://fukuoka-orientalhotel.com/',
  },
  days: [
    {
      day: 1,
      title: 'Day 1',
      date: '2026-09-03',
      title: '抵達福岡！博多美食、大濠公園、福岡塔夜景',
      icon: '🧳',
      schedule: [
        {
          time: '09:55',
          title: '抵達福岡機場',
          category: '交通',
          location: '福岡機場',
          note: '入境、領行李後前往市區。',
          image: '',
          links: [
            {
              label: 'Google Maps',
              url: 'https://www.google.com/maps/search/?api=1&query=Fukuoka+Airport',
            },
          ],
        },
        {
          time: '11:00',
          title: '飯店寄放行李',
          category: '住宿',
          location: '福岡博多車站東方飯店',
          note: '15:00後可辦理入住，先寄放行李再出發。',
          image: '',
          links: [],
        },
        {
          time: '12:00',
          title: '博多午餐 排隊吃Musashi和牛飯！',
          category: '用餐',
          location: '博多車站、博多運河附近吃東西',
          note: ' 備案：一蘭 博多運河城店(才有方形盒子)、いくら蛋包飯',
          image: '',
          links: [
            {
              label: 'Musashi 黒毛和牛 博多牛まぶし 武蔵',
              url: 'https://maps.app.goo.gl/FqP1VQmCW9YjCu5n6',
            },
            {
              label: '一蘭拉麵',
              url: 'https://maps.app.goo.gl/gipsA2r1w2VMnzLT6',
            },
            {
              label: 'いくら博多店',
              url: 'https://maps.app.goo.gl/HU2LKdLCpEoF32Hs5',
            },
          ],
        },
        {
          time: '14:00',
          title: '來個小甜點',
          category: '美食',
          location: 'いもんね博多店',
          openingHours: '10:00-21:00',
          note: '冰淇淋麻吉店 小乖推推 感覺好吃很可愛 在博多車站 & 飯店附近',
          image: '',
          links: [
            {
              label: 'いもんね博多店',
              url: 'https://www.google.com/maps/search/?api=1&query=Kushida+Shrine+Fukuoka',
            },
          ],
        },
        {
          time: '15:00',
          title: '飯店Check In(也可以之後再入住 都可) + 小逛街',
          category: '住宿',
          location: '博多車站、飯店、Nintendo FUKUOKA',
          openingHours: 'Nintendo FUKUOKA 10:00-20:00',
          note: '準備去公園玩的食物(微野餐)、Nintendo FUKUOKA買皮克敏、飯店check in',
          image: '',
          links: [
            {
              label: 'Nintendo FUKUOKA',
              url: 'https://maps.app.goo.gl/sZnnKRKHbyVgpPMX9',
            },
            {
              label: 'Dacomecca 麵包店',
              url: 'https://maps.app.goo.gl/bDU4MWogjXCnbUGG7',
            },
          ],
        },
        {
          time: '16:00',
          title: '大濠公園 & 福岡市美術館',
          category: '景點',
          location: '大濠公園',
          note: '福岡城、舞鶴公園、福岡市美術館（草間彌生南瓜）、大濠公園、逛逛吃吃',
          image: '',
          links: [],
        },
        {
          time: '17:45',
          title: '福岡的街邊夕陽與海',
          category: '景點',
          location: '福岡塔 & 百道濱海灘',
          note: '看漂亮夕陽與海景，很餓的話就找地方吃東西、不看夕陽的話：可以和上一個行程對調，比較好安排晚餐時間',
          image: '',
          links: [
            {
              label: '福岡塔',
              url: 'https://maps.app.goo.gl/H9NTiR55AayksERK9',
            },
          ],
        },
        {
          time: '19:00',
          title: '享受晚餐 博多水炊鍋専門 橙',
          category: '用餐',
          location: '大濠公園站吃',
          note: '訂好位了，遺珠還是留著',
          image: '',
          links: [
            {
              label: '博多水炊鍋専門 橙',
              url: 'https://maps.app.goo.gl/PYwSY9o9M6TgkYxB9',
            },
            {
              label: 'Ishihara 石原牛精肉店',
              url: 'https://maps.app.goo.gl/ytZFega9ko5Z3DTW8',
            },
            {
              label: 'WAGYU PINFU 日式燒肉餐廳',
              url: 'https://maps.app.goo.gl/YMeo6m57EPVTfa9G8',
            },
          ],
        },
        {
          time: '20:30',
          title: '回飯店休息 & 車站地下街逛逛採買',
          category: '住宿',
          location: '博多車站',
          note: '回到飯店休息、博多車站地下街逛逛、第一波伴手禮採買',
          image: '',
          links: [],
        },
      ],
    },
    {
      day: 2,
      date: '2026-09-04',
      title: '櫛田神社、Mina逛街、吃爐端燒',
      icon: '⛩️',
      schedule: [
        {
          time: '08:00',
          title: '飯店早餐 & 準備出發',
          category: '用餐',
          location: '東方飯店',
          openingHours: '還沒確認早餐時間',
          note: '吃早餐、準備出發！要留胃給中午吃拉麵，所以早點吃早餐',
          image: '',
          links: [],
        },
        {
          time: '09:30',
          title: '櫛田神社',
          category: '景點',
          location: '櫛田神社',
          note: '參拜、街道逛街',
          image: '',
          links: [
            {
              label: '櫛田神社',
              url: 'https://www.google.com/maps/search/?api=1&query=Dazaifu+Tenmangu',
            },
            { label: '更多資訊', url: 'https://www.dazaifutenmangu.or.jp/' },
          ],
        },
        {
          time: '11:00',
          title: '排隊吃 Shin Shin 拉麵',
          category: '用餐',
          location: '大濠公園站吃',
          note: '11:00開，看要不要提前排隊',
          image: '',
          links: [
            {
              label: 'Shin Shin 拉麵',
              url: 'https://maps.app.goo.gl/LbvS1sFmEMJJGfAf8',
            },
          ],
        },
        {
          time: '13:30',
          title: '天神・大名逛街',
          category: '購物',
          location: '天神 / 大名',
          note: '咖啡、選物店、百貨都可依體力彈性調整。',
          image: '',
          links: [],
        },
        {
          time: '16:00',
          title: '16:30 爐端燒',
          category: '用餐',
          location: 'Musashiza すみ劇場 むさし坐',
          note: '1樓氣氛很棒，推薦食物：炸雞、喜知次魚、牛肉串、甜點',
          image: '',
          links: [],
        },
        {
          time: '19:00',
          title: '夜間散步逛街+買宵夜',
          category: '逛街',
          location: 'Mina / Muji',
          note: '如果想體驗屋台，可以晚餐後再去逛逛感受氣氛+買章魚燒之類的',
          image: '',
          links: [],
        },
      ],
    },
    {
      day: 3,
      date: '2026-09-05',
      title: '大採買日・返程',
      icon: '🛍️',
      schedule: [
        {
          time: '08:00',
          title: '飯店早餐 & 收拾行李',
          category: '用餐',
          location: '東方飯店',
          openingHours: '還沒確認早餐時間',
          note: '吃早餐、準備回程行李，確認伴手禮與隨身物品。',
          image: '',
          links: [],
        },
        {
          time: '11:00',
          title: '午餐',
          category: '美食',
          location: '福岡',
          note: '還沒安排，看還有甚麼想吃還沒吃的，之前的遺珠（不過這一天有行李、看要不要繼續借放飯店？）',
          image: '',
          links: [],
        },
        {
          time: '13:00',
          title: '繼續大採購：買麵包、明太子醬、超市點心、藥妝衣服鞋子',
          category: '購物',
          location: '',
          note: '確認伴手禮的數量與重量、注意託運！',
          image: '',
          links: [],
        },
        {
          time: '15:30',
          title: '回飯店取行李(加上放行李托運)、準備前往機場',
          category: '住宿',
          location: '住宿地點',
          note: '確認伴手禮與隨身物品。',
          image: '',
          links: [],
        },
        {
          time: '16:00',
          title: '前往福岡機場',
          category: '交通',
          location: '福岡機場',
          note: '託運排隊、吃完福岡機場的海鮮丼再去登機、爆買餅乾糖果、最後的伴手禮採買',
          image: '',
          links: [],
        },
        {
          time: '18:10',
          title: '19:10 搭機回台灣',
          category: '交通',
          location: '福岡機場',
          note: '',
          image: '',
          links: [],
        },
      ],
    },
  ],
  footer: {
    message: 'Have a nice trip ♡',
    updatedAt: '2026-08-28',
  },
}
